import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary":           "#007AFF",
        "primary-fixed":     "#007AFF",
        "primary-dim":       "#0055CC",
        "primary-container": "#E3F0FF",
        "on-primary":        "#ffffff",
        "secondary":         "#34C759",
        "secondary-container": "#E8F8EC",
        "tertiary":          "#FF9500",
        "tertiary-dim":      "#CC7700",
        "tertiary-container":"#FFF3E0",
        "background":        "#F2F2F7",
        "surface":           "#FFFFFF",
        "surface-container": "#F2F2F7",
        "surface-container-high": "#E5E5EA",
        "surface-container-highest": "#D1D1D6",
        "on-surface":        "#1C1C1E",
        "on-surface-variant":"#3C3C43",
        "outline":           "#C6C6C8",
        "outline-variant":   "#E5E5EA",
        "error":             "#FF3B30",
        "error-container":   "#FFE5E3",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        md:      "0.75rem",
        lg:      "1rem",
        xl:      "1.5rem",
        "2xl":   "1rem",
        "3xl":   "1.25rem",
        full:    "9999px",
      },
      fontFamily: {
        headline: ["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "Helvetica Neue", "sans-serif"],
        body:     ["-apple-system", "BlinkMacSystemFont", "SF Pro Text", "Helvetica Neue", "sans-serif"],
        label:    ["-apple-system", "BlinkMacSystemFont", "SF Pro Text", "Helvetica Neue", "sans-serif"],
        editorial:["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "Helvetica Neue", "sans-serif"],
        display:  ["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "Helvetica Neue", "sans-serif"],
      },
      spacing: {
        "0.5": "0.125rem",
        "1":   "0.25rem",
        "2":   "0.5rem",
        "3":   "0.75rem",
        "4":   "1rem",
        "5":   "1.25rem",
        "6":   "1.5rem",
        "8":   "2rem",
        "10":  "2.5rem",
        "12":  "3rem",
        "16":  "4rem",
        "20":  "5rem",
        "24":  "6rem",
      },
      scale: { "102": "1.02" },
      animation: {
        "fade-in":  "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.3s cubic-bezier(0.33, 1, 0.68, 1)",
        "slide-in-left": "slideInLeft 0.3s cubic-bezier(0.33, 1, 0.68, 1)",
      },
      keyframes: {
        fadeIn:  { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp: { "0%": { transform: "translateY(10px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        slideInLeft: { "0%": { transform: "translateX(-100%)" }, "100%": { transform: "translateX(0)" } },
      },
    },
  },
  plugins: [],
};

export default config;
