import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary":           "#FFD60A",
        "primary-fixed":     "#FFD60A",
        "primary-dim":       "#E6C000",
        "primary-container": "#2A2400",
        "on-primary":        "#0C0C0C",
        "secondary":         "#FF3D9A",
        "secondary-container": "#2A0018",
        "tertiary":          "#FFB830",
        "tertiary-dim":      "#E6A020",
        "tertiary-container":"#2A1800",
        "background":        "#0C0C0C",
        "surface":           "#1A1A1A",
        "surface-container": "#141414",
        "surface-container-high": "#222222",
        "surface-container-highest": "#2A2A2A",
        "on-surface":        "#FFFDE7",
        "on-surface-variant":"#FF9FCA",
        "outline":           "#3A3A3A",
        "outline-variant":   "#2A2A2A",
        "error":             "#FF3D9A",
        "error-container":   "#2A0018",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        md:      "0.75rem",
        lg:      "1rem",
        xl:      "1.5rem",
        "2xl":   "1rem",
        "3xl":   "1.25rem",
        full:    "9999px",
      },
      fontFamily: {
        headline: ["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "Helvetica Neue", "sans-serif"],
        body:     ["-apple-system", "BlinkMacSystemFont", "SF Pro Text", "Helvetica Neue", "sans-serif"],
        label:    ["-apple-system", "BlinkMacSystemFont", "SF Pro Text", "Helvetica Neue", "sans-serif"],
        editorial:["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "Helvetica Neue", "sans-serif"],
        display:  ["-apple-system", "BlinkMacSystemFont", "SF Pro Display", "Helvetica Neue", "sans-serif"],
      },
      spacing: {
        "0.5": "0.125rem",
        "1":   "0.25rem",
        "2":   "0.5rem",
        "3":   "0.75rem",
        "4":   "1rem",
        "5":   "1.25rem",
        "6":   "1.5rem",
        "8":   "2rem",
        "10":  "2.5rem",
        "12":  "3rem",
        "16":  "4rem",
        "20":  "5rem",
        "24":  "6rem",
      },
      scale: { "102": "1.02" },
      animation: {
        "fade-in":  "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.3s cubic-bezier(0.33, 1, 0.68, 1)",
        "slide-in-left": "slideInLeft 0.3s cubic-bezier(0.33, 1, 0.68, 1)",
      },
      keyframes: {
        fadeIn:  { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        slideUp: { "0%": { transform: "translateY(10px)", opacity: "0" }, "100%": { transform: "translateY(0)", opacity: "1" } },
        slideInLeft: { "0%": { transform: "translateX(-100%)" }, "100%": { transform: "translateX(0)" } },
      },
    },
  },
  plugins: [],
};

export default config;
